# -*- coding: utf-8 -*-
"""Survival Duration Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yc5R8GCrSEJGFDLX4tIduNO5rcM1R28D
"""

class AgeCalc:
  def __init__(self, age):
    self.age = age

  def months(self):
    return self.age * 12

  def weeks(self):
    return self.age * 52.143

  def days(self):
    return self.age * 365.25

  def hours(self):
    return self.days() * 24

  def minutes(self):
    return self.hours() * 60

  def seconds(self):
    return self.minutes() * 60

  def unit(self, choice):
        if choice == 'months' or choice == 'm':
            return "You lived for {:.2f} Months.".format(self.months())
        elif choice == 'weeks' or choice == 'w':
            return "You lived for {:.2f} Weeks.".format(self.weeks())
        elif choice == 'days' or choice == 'd':
            return "You lived for {:.2f} Days.".format(self.days())
        elif choice == 'hours' or choice == 'h':
            return "You lived for {:.2f} Hours.".format(self.hours())
        elif choice == 'minutes' or choice == 'min':
            return "You lived for {:.2f} Minutes.".format(self.minutes())
        elif choice == 'seconds' or choice == 's':
            return "You lived for {:.2f} Seconds.".format(self.seconds())
        else:
            return "Invalid choice. Please run the program again."

  def main():
    while True:
      try:
        age = float(input("Enter your age: "))
        if age < 0:
          raise ValueError("Age cannot be negative.")
        break
      except ValueError as e:
        print(f"Invalid input: {e}. Please enter a valid age.")

    yourage = AgeCalc(age)

    print("\nSelect the output you want (you can type the first letter or the full name):\n- Months / 'm'\n- Weeks / 'w'\n- Days / 'd'\n- Hours / 'h'\n- Minutes / 'min'\n- Seconds / 's'")

    choice = input("Enter your choice: ").lower()

    result = yourage.unit(choice)
    print(result)

  main()